In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

# Q3. Singular Value Decomposition (SVD):
Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print matrices U, Σ, and 𝑉 ் . Verify that A equals the product of U, Σ, and 𝑉 ் . Additionally, find the rank 2 and rank 3 approximations of matrix A.

In [3]:
A = np.random.randint(0, 10, size=(5, 5))
print("Original matrix A:")
print(A)

Original matrix A:
[[4 4 0 3 2]
 [0 8 2 4 4]
 [4 2 4 3 6]
 [5 4 9 1 4]
 [9 8 3 3 9]]


In [4]:
#Q 3
 # Perform Singular Value Decomposition (SVD)
U, Sigma, V_transpose = np.linalg.svd(A)
Sigma_mat = np.zeros_like(A, dtype=float)
Sigma_mat[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(Sigma)
print("Matrix U:")
print(U)
print("\nMatrix Sigma:")
print(Sigma_mat)
print("\nMatrix V:")
print(V_transpose.T)

Matrix U:
[[-0.26053803 -0.31091481 -0.19370591  0.3830551  -0.80696885]
 [-0.35998578 -0.55188094  0.73541383 -0.12937844  0.09091412]
 [-0.37419323  0.21724117 -0.12585712 -0.83067771 -0.32698659]
 [-0.45354111  0.7183493   0.3862753   0.35509942 -0.05450259]
 [-0.67587725 -0.18852046 -0.50655295  0.14285991  0.48025528]]

Matrix Sigma:
[[22.57744637  0.          0.          0.          0.        ]
 [ 0.          7.40748373  0.          0.          0.        ]
 [ 0.          0.          5.61463422  0.          0.        ]
 [ 0.          0.          0.          2.97517161  0.        ]
 [ 0.          0.          0.          0.          2.00308183]]

Matrix V:
[[-0.48231876  0.20524754 -0.69565567  0.42711683 -0.24264472]
 [-0.52670294 -0.5209584   0.4184512   0.47026344  0.23438696]
 [-0.368786    0.76473811  0.52082076  0.01445524 -0.08780252]
 [-0.25801455 -0.31532391  0.15131577 -0.36189591 -0.8247025 ]
 [-0.53607649 -0.04714061 -0.21635862 -0.68208937  0.44535694]]


In [5]:
# Now we show that A equals the product of U, Sigma, and V
A_reconstructed = np.dot(U, np.dot(Sigma_mat, V_transpose))
print("\nVerification that A equals the product of U, Sigma, and V:")
print(np.allclose(A, A_reconstructed))


Verification that A equals the product of U, Sigma, and V:
True
